site_name: AWS Baseline
site_url: https://timoguin.github.io/aws-baseline
repo_url: https://github.com/timoguin/aws-baseline

# Automatically set to GitHub
repo_name: null # Automatically set to GitHub

# Doesn't need to be set for GitHub Pages (derived from the site_url
edit_uri: null

site_description: Baseline requirements to install in all AWS accounts, documented and codified
site_author: Tim O'Guin
copyright: © 2019 Tim O'Guin

# Analytics tracking for the site_url
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_TOKEN"]
  - auto

# Defaults to the origin/gh-pages branch
remote_branch: null
remote_name: null

nav:
   - Overview: overview.md
   - Goals: goals.md
   - Spec:
     - Index: spec/index.md
     - CloudTrail: spec/cloudtrail/index.md 
     - Config: spec/config/index.md 
     - S3: spec/s3/index.md 
     - Logging: spec/logging.md
   - Code: code/index.md
   # - Advanced: advanced.md
   # - Costs: costs.md
   # - Issue Tracker: https://github.com/timoguin/aws-baseline/issues

theme:
  name: material
  language: en
  favicon: images/favicon.ico
  logo: images/aws-baseline-logo.png
  feature:
    - tabs: true
  palette:
    primary: orange
    accent: blue grey
  font:
    text: Roboto
    code: Roboto Mono
  # custom_dir:
  # static_templates:
  #   -

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Defaults to docs/
docs_dir: null

# Defaults to site/
site_dir: null

# extra_css:
#   -

# extra_javascript:
#   -

# extra_templates:
#   -

extra:
  version: 0.1.2
  search:
    language: en
    tokenizer: '[\s\-\.]+'
  # manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/timoguin'

plugins:
  - search:
      lang: en
